spring:
  profiles: inmemory
  application:
    name: spring-northwind

datasource:
  url: jdbc:h2:mem:test-db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  platform: h2
  username: sa
  password:
  driver-class-name: org.h2.Driver

h2:
  console:
    enabled: true
    path: /h2-console
